### ISSUE TITLE
how to get the srcipt？

### ISSUE THREAD

**Issue by cswp4** [person594/regccrf-experiments#2]
Hi，I follow your preparation instructions on the corpus conll-2012 - according to https://cemantix.org/data/ontonotes.html. 

But I can't download the script.
<img width="694" alt="image" src="https://github.com/person594/regccrf-experiments/assets/115931435/281b960e-aedf-400b-8fdf-7b3961737794">

Is there any important informations I have missed? 
Can u share the script?  Or even the Conll-2012 corpus that you used. 

Thx!

**Comment by person594** [comment]
I don't think I can share the full corpus for copyright reasons, but I found the scripts still available [here](https://conll.cemantix.org/2012/data.html). No idea why they disappeared from the other page...

**Comment by Joel4U** [comment]
> I don't think I can share the full corpus for copyright reasons, but I found the scripts still available [here](https://conll.cemantix.org/2012/data.html). No idea why they disappeared from the other page...

Thank you, Best!
